services:
  sysspec-tool:
    build: .
    container_name: sysspec_cli
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    stdin_open: true
    tty: true
    read_only: true
    environment:
      - SYSSPEC_HOST_ROOT=/host