name: C++ Native Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build -S .
      - name: Build Project
        run: cmake --build build
      - name: Run Tests
        working-directory: build
        run: ctest || echo "No tests defined"